"""add_storage_key_to_duma_stored_files

Revision ID: 0164523ba90b
Revises: b1393c63044d
Create Date: 2026-01-21 16:25:30.827401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0164523ba90b'
down_revision: Union[str, None] = 'b1393c63044d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duma_stored_files', sa.Column('storage_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duma_stored_files', 'storage_key')
    # ### end Alembic commands ###

