"""add_dumapod_connection_status

Revision ID: 4e35381f395b
Revises: fea8c0ba5f13
Create Date: 2026-02-05 13:29:57.723816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e35381f395b'
down_revision: Union[str, None] = 'fea8c0ba5f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dumapods', sa.Column('connection_status', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dumapods', 'connection_status')
    # ### end Alembic commands ###

