"""add_pod_description

Revision ID: 4eaeacde8376
Revises: 7bd28d55305b
Create Date: 2026-02-05 13:04:36.092874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eaeacde8376'
down_revision: Union[str, None] = '7bd28d55305b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dumapods', sa.Column('pod_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dumapods', 'pod_description')
    # ### end Alembic commands ###

