"""add_duma_stored_files_table

Revision ID: 8c1df4b018aa
Revises: e763a94f89f9
Create Date: 2026-01-14 14:06:35.335250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1df4b018aa'
down_revision: Union[str, None] = 'e763a94f89f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duma_stored_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dumapod_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('wasabi_url', sa.String(), nullable=True),
    sa.Column('oracle_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dumapod_id'], ['dumapods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duma_stored_files_dumapod_id'), 'duma_stored_files', ['dumapod_id'], unique=False)
    op.create_index(op.f('ix_duma_stored_files_id'), 'duma_stored_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duma_stored_files_id'), table_name='duma_stored_files')
    op.drop_index(op.f('ix_duma_stored_files_dumapod_id'), table_name='duma_stored_files')
    op.drop_table('duma_stored_files')
    # ### end Alembic commands ###

