"""create dumapods table

Revision ID: c19e862a5d9f
Revises: de683bd72412
Create Date: 2026-01-14 11:33:44.406309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19e862a5d9f'
down_revision: Union[str, None] = 'de683bd72412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dumapods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_capacity_gb', sa.Integer(), nullable=False),
    sa.Column('enable_s3', sa.Boolean(), nullable=False),
    sa.Column('enable_wasabi', sa.Boolean(), nullable=False),
    sa.Column('enable_oracle_os', sa.Boolean(), nullable=False),
    sa.Column('primary_storage', sa.Enum('AWS_S3', 'WASABI', 'ORACLE_OS', name='storageprovider'), nullable=False),
    sa.Column('secondary_storage', sa.Enum('AWS_S3', 'WASABI', 'ORACLE_OS', name='storageprovider'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('amount_in_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dumapods_id'), 'dumapods', ['id'], unique=False)
    op.create_index(op.f('ix_dumapods_name'), 'dumapods', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dumapods_name'), table_name='dumapods')
    op.drop_index(op.f('ix_dumapods_id'), table_name='dumapods')
    op.drop_table('dumapods')
    # ### end Alembic commands ###

