"""relax_dumapod_requirements

Revision ID: d2e7e961962c
Revises: 4eaeacde8376
Create Date: 2026-02-05 13:06:02.157334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e7e961962c'
down_revision: Union[str, None] = '4eaeacde8376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dumapods', 'storage_capacity_gb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dumapods', 'primary_storage',
               existing_type=postgresql.ENUM('AWS_S3', 'WASABI', 'ORACLE_OS', name='storageprovider'),
               nullable=True)
    op.alter_column('dumapods', 'amount_in_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dumapods', 'amount_in_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('dumapods', 'primary_storage',
               existing_type=postgresql.ENUM('AWS_S3', 'WASABI', 'ORACLE_OS', name='storageprovider'),
               nullable=False)
    op.alter_column('dumapods', 'storage_capacity_gb',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

