"""add_storage_credentials

Revision ID: e763a94f89f9
Revises: c19e862a5d9f
Create Date: 2026-01-14 12:53:13.483042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e763a94f89f9'
down_revision: Union[str, None] = 'c19e862a5d9f'
branch_labels: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'storage_credentials' not in tables:
        from sqlalchemy.dialects import postgresql
        
        # Define enum type explicitly
        storage_provider_enum = postgresql.ENUM('AWS_S3', 'WASABI', 'ORACLE_OS', name='storageprovider', create_type=False)
        
        op.create_table('storage_credentials',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('dumapod_id', sa.Integer(), nullable=False),
            sa.Column('provider', storage_provider_enum, nullable=False),
            sa.Column('access_key', sa.String(), nullable=False),
            sa.Column('secret_key', sa.String(), nullable=False),
            sa.Column('bucket_name', sa.String(), nullable=False),
            sa.Column('endpoint_url', sa.String(), nullable=True),
            sa.Column('region', sa.String(), nullable=True),
            sa.Column('namespace', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['dumapod_id'], ['dumapods.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_storage_credentials_id'), 'storage_credentials', ['id'], unique=False)
    
    columns = [c['name'] for c in inspector.get_columns('dumapods')]
    
    if 'use_custom_s3' not in columns:
        op.add_column('dumapods', sa.Column('use_custom_s3', sa.Boolean(), server_default='false', nullable=False))
    if 'use_custom_wasabi' not in columns:
        op.add_column('dumapods', sa.Column('use_custom_wasabi', sa.Boolean(), server_default='false', nullable=False))
    if 'use_custom_oracle' not in columns:
        op.add_column('dumapods', sa.Column('use_custom_oracle', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dumapods', 'use_custom_oracle')
    op.drop_column('dumapods', 'use_custom_wasabi')
    op.drop_column('dumapods', 'use_custom_s3')
    op.drop_index(op.f('ix_storage_credentials_id'), table_name='storage_credentials')
    op.drop_table('storage_credentials')
    # ### end Alembic commands ###

