"""add_multipart_upload_fields

Revision ID: f1c1033ba1f7
Revises: 0164523ba90b
Create Date: 2026-01-21 17:24:13.535649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c1033ba1f7'
down_revision: Union[str, None] = '0164523ba90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duma_stored_files', sa.Column('multipart_upload_id', sa.String(), nullable=True))
    op.add_column('duma_stored_files', sa.Column('total_parts', sa.Integer(), nullable=True))
    op.add_column('duma_stored_files', sa.Column('uploaded_parts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duma_stored_files', 'uploaded_parts')
    op.drop_column('duma_stored_files', 'total_parts')
    op.drop_column('duma_stored_files', 'multipart_upload_id')
    # ### end Alembic commands ###

