"""set_dumapod_defaults

Revision ID: fea8c0ba5f13
Revises: d2e7e961962c
Create Date: 2026-02-05 13:13:00.693620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea8c0ba5f13'
down_revision: Union[str, None] = 'd2e7e961962c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

